branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: Test
  default_ec2_keyname: qazwsx
  default_platform: Python 2.7
  default_region: us-west-2
  profile: eb-cli
  sc: git
